version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd server
      - npm install
      - echo Creating Database...
      - echo Migrating Database to Latest...
      - npm run migrate
  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - /server/src/**/*
    - knexfile.js
    - db.js
    - package.json
    - node_modules/**/*